#!/usr/bin/env node --harmony

/**
 * Module dependencies.
 */

var co = require('co');
var fsq = require('./foursquare');
var db = require('./db');

/**
 * Run.
 */

co(function *() {
  var res = yield fsq.trending();
  if (!res || res.meta.code !== 200) throw new Error('Oops.');
  return yield db.add(res.response.venues);
});
